name: CI

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'

    - name: Extract Version from Gradle
      id: extract_version
      run: |
        VERSION=$(grep -oP '^version\s*=\s*"\K[^\"]+' build.gradle.kts)
        echo "version=$VERSION" >> $GITHUB_ENV

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: parser-combinators
        path: build/libs/parser-combinators-${{ env.version }}.jar

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download JAR
      uses: actions/download-artifact@v4
      with:
        name: parser-combinators
        path: build/libs

    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: Release ${{ github.ref_name }}
        files: build/libs/parser-combinators-*.jar
        draft: false
        prerelease: false
